# Generated by Django 5.1.15 on 2026-10-07 21:10

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models
from pgvector.django import VectorExtension
import documents.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the document', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Document title / original filename', max_length=255)),
                ('file', models.FileField(blank=True, help_text='Uploaded source file', null=True, upload_to='documents/%Y/%m/')),
                ('file_type', models.CharField(default='application/octet-stream', help_text='Detected MIME type (via magic bytes)', max_length=50)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('storage_key', models.CharField(blank=True, help_text='Storage identifier / S3 object key', max_length=500)),
                ('content_hash', models.CharField(db_index=True, help_text='SHA-256 hash of file content for deduplication', max_length=64)),
                ('visibility', models.CharField(choices=[('private', 'Private (Owner Only)'), ('group', 'Group Restricted'), ('tenant', 'Tenant-Wide')], default='private', help_text='Access control visibility scope', max_length=20)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='uploaded', help_text='Current ingestion state', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error details if ingestion failed')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Arbitrary document metadata (page count, headers, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='User who uploaded this document', on_delete=django.db.models.deletion.CASCADE, related_name='owned_documents', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(help_text='Tenant that owns this document', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField(help_text='Sequence index of the chunk within the parent document (0-indexed)')),
                ('text', models.TextField(help_text='Extracted chunk text passage')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536, help_text='1,536-dimensional dense vector embedding')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Chunk-level metadata (token count, character offset, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='tenants.tenant')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.document')),
            ],
            options={
                'verbose_name': 'Chunk',
                'verbose_name_plural': 'Chunks',
                'ordering': ['document', 'position'],
            },
        ),
        migrations.CreateModel(
            name='DocumentPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='documents.document')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_permissions', to='tenants.group')),
            ],
            options={
                'verbose_name': 'Document Permission',
                'verbose_name_plural': 'Document Permissions',
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['tenant', 'status'], name='documents_d_tenant__1461e3_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['tenant', 'content_hash'], name='documents_d_tenant__55a1c7_idx'),
        ),
        migrations.AddIndex(
            model_name='chunk',
            index=models.Index(fields=['tenant', 'document'], name='documents_c_tenant__d18c35_idx'),
        ),
        migrations.AddIndex(
            model_name='chunk',
            index=documents.models.CompatibleHnswIndex(ef_construction=64, fields=['embedding'], m=16, name='chunk_vec_hnsw_idx', opclasses=['vector_cosine_ops']),
        ),
        migrations.AlterUniqueTogether(
            name='documentpermission',
            unique_together={('document', 'group')},
        ),
    ]
